### ISSUE TITLE
Checklist for Song/Group Markup

### ISSUE THREAD

**Issue by PiperBaron** [PiperBaron/KPopRepo#8]
Just thought this would be useful to visualize how much we've done/have to do!

## Checklist
- [x] BTS Profile/Boy with Luv
- [x] Twice Profile/Likey
- [x] Blackpink Profile/DDU-DU DDU-DU 
- [x] EXO Profile/Obsession
- [x] GOT7 Profile/Lullaby
- [x] Seventeen Profile/Don't Wanna Cry
- [x] NCT 127 Profile/Simon Says
- [x] NCT Dream Profile/Ridin'
- [x] Monsta X Profile/Love Killa
- [x] Stray Kids Profile/Back Door
